on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Verificando repositório do Git
        uses: actions/checkout@v2

      - name: Instalando node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Instando dependências
        run: npm install
      
      - name: Executando ESlint
        run: npx eslint .
    
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - name: Verificando repositório do Git
        uses: actions/checkout@v2
      
      - name: Instalando node
        uses: actions/setup-node@v1
      
      - name: Instalando dependências
        run: npm install
      
      - name: Executando Stylelint
        run: npm run lint:styles

  evaluator:
    runs-on: ubuntu-latest
    steps:
      - name: Verificando repositório do Git
        uses: actions/checkout@v2

      - name: Instalando node
        uses: actions/setup-node@v1
      
      - name: Instalando dependências
        run: npm install

      - name: Executando testes
        run: npm test
