on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Verificando repositório do Git
        uses: actions/checkout@v2
      
      - name: Instalando node
        uses: actions/setup-node@v1
        with:
          node-version: 14
        
      - name: Build da aplicação
        run: |
          npm ci
          npm run test:dev
          npm run build

      - name: Deploy para Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build